### PR TITLE
Fix distorted outputs by using correct padding when reading/writing gl image data.

### LINKED ISSUE #7: rendering bug for some aspect ratios
There's currently an bug where some video dimensions result in warped, funky-looking transitions.

I'm not sure exactly what the bug is, but my best guess is that it has to do with how AVFrame represents its frame data.  It seems that AVFrame adds [padding](https://ffmpeg.org/doxygen/2.7/structAVFrame.html#aa52bfc6605f6a3059a0c3226cc0f6567) to each line to maximize use of SIMD.  We're definitely not accounting for this padding, and I think that's what's causing the issue for some video sizes.

Adding this here to track progress.

### PR DESCRIPTION
**Pull request by jviney**
Fixes #7.

### CODE REVIEW

**Comment by transitive-bullshit** [comment]
This looks perfect @jviney -- thank you so much! 👍 

Give me a day or so to test locally.

**Comment by CoreTechie** [comment]
Does this also fixes Issue #28 ? Issue with all resolutions (including 1920 x 1080) having 16:9 aspect ratio ?

**Comment by transitive-bullshit** [comment]
It should @CoreTechie. Please follow-up if you're still experiencing issues.

**Comment by CoreTechie** [comment]
This doesn't seem to address the issue of cropping at the top and right edges of the frame of dims 1920 x 1080. A few rows at the top edge and couple of columns on the right edge are getting clipped. Has it something to do with the Magnification or Minification filters while the image data is mapped onto the texture ? 

glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR); glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR);

**Comment by CoreTechie** [comment]
Hi Travis (@transitive-bullshit ) - Could you reproduce the problem with 1920 x 1080. What could be the possible causes for the cross-faded picture being shrunk. Also it seems the picture is slightly vertically shifted down including clipping on both top and right edges.  Thanks !

**Comment by yukesh0505** [comment]
Hi, I have the same bug. For some aspect ratio, rendered video didn't produce actual transition some funky transition occurs. please give me some suggestions

**Pull request merged**
