### PR TITLE
use EGL in linux

### PR DESCRIPTION
**Pull request by turengege**
hi
Thanks for sharing this project!
I have being using ffmpeg-gl-transition  in production(headless environment).

But I found Xvfb just ignores my Nvidia GPU devices and use CPU to do the rendering. 
So I use EGL instead which is more convenient in headless environment and  rendering using GPU.

### CODE REVIEW

**Comment by transitive-bullshit** [comment]
This is really awesome, @turengege!

Any idea if this addresses #7 on non-apple environments?

I'll need a bit of time to digest these changes and test things, as I'm not too familiar with EGL, but honestly this looks great and I'm really glad you decided to contribute back!

**Comment by transitive-bullshit** [comment]
@turengege @gre does EGL no longer require you to use xvfb+libmesa on headless environments?

**Comment by transitive-bullshit** [comment]
From my understanding, we still need to have `libmesa` installed on headless linux, but `xvfb` is no longer necessary. Is this correct?

@turengege would you mind providing (or linking to) headless setup instructions for making sure `EGL` will work correctly?

Thanks!

**Comment by turengege** [comment]
@transitive-bullshit
Yes it's correct, glfw and Xvfb is not required any more. 
and glew 2.0 or higher is required.

I used libmesa1.7,libmesaGLU1.7,GLEW 2.1,glvnd1.0.
Actually I just add libmesaGLU1.7 and GLEW 2.1 based on `nvidia/cudagl:9.0-devel-centos7`(docker image)

**Comment by turengege** [comment]
This commit is only about linux. On mac it's still using AGL and GLFW is required. 
 EGL seems not supported on mac now.

**Comment by transitive-bullshit** [comment]
@turengege -- awesome, really appreciate your work on this!

Out of curiosity, what are you using this for in production? (totally ok if it's confidential)

**Comment by yinjiaoyuan** [comment]
> @transitive-bullshit Yes it's correct, glfw and Xvfb is not required any more. and glew 2.0 or higher is required.
> 
> I used libmesa1.7,libmesaGLU1.7,GLEW 2.1,glvnd1.0. Actually I just add libmesaGLU1.7 and GLEW 2.1 based on `nvidia/cudagl:9.0-devel-centos7`(docker image)

How to make GLEW2.1? make SYSTEM=linux-egl? Thanks.

**Comment by yinjiaoyuan** [comment]
> @transitive-bullshit Yes it's correct, glfw and Xvfb is not required any more. and glew 2.0 or higher is required.
> 
> I used libmesa1.7,libmesaGLU1.7,GLEW 2.1,glvnd1.0. Actually I just add libmesaGLU1.7 and GLEW 2.1 based on `nvidia/cudagl:9.0-devel-centos7`(docker image)

@turengege How to make GLEW2.1? make SYSTEM=linux-egl? Thanks.

**Pull request merged**
